### PR TITLE
Frontend update

### PR DESCRIPTION
**Pull request by Xpirix**
Homepage:
image

Plugins List:
image

### CODE REVIEW

**Comment by timlinux** [comment]
That is looking fantastic @Xpirix !

**Comment by Xpirix** [comment]
## Latest update

plugins_homepage

Screenshot 2024-09-28 at 12 19 55 PM

Screenshot 2024-09-28 at 12 20 24 PM

Screenshot 2024-09-28 at 12 19 16 PM

Screenshot 2024-09-28 at 12 19 32 PM

**Comment by agiudiceandrea** [comment]
@Xpirix using Google Chrome 129.0.6668.70 on Windows 10
image

**Comment by Xpirix** [comment]
Thanks for the review @agiudiceandrea. Managing the table is a bit tricky as we have large left and right margins on the new branding. Indeed, the table becomes scrollable vertically on a smaller screen. What do you think about keeping the grid view only? Or we can also hide some columns on a smaller screen (depending on the priority of the columns)

**Comment by agiudiceandrea** [comment]
> the table becomes scrollable horizontally on a smaller screen
I've missed the horizontal scroll bar... Having the horizontal scroll bar at the bottom and at the top would be useful.
My screen is not actually small, it's 1366x768. Isn't possible to reduce the left and right margins?

> What do you think about keeping the grid view only?

I think the table view is needed. I've also noticed that the choice between grid and table view doesn't stick: if you choose the table view and then click on the "Next" button, then the list is shown again as a grid. The same occurs if you go from e.g. the "All plugins" list to the "New plugins" list.

> Or we can also hide some columns

I think, on the contrary, that there are missing columns, like the "Created on" column and the latest version number.

It seems to me the "Stable" list should not be in "Top", but probably in "Categories".
I would suggest to add a simple description on each list page on how the list is generated / sorted (e.g. the "Popular" list name is not self explanatory).

**Comment by Xpirix** [comment]
> Having the horizontal scroll bar both at the bottom and at the top would be useful.

I agree, I've also had that idea but didn't implement it yet.

> My screen is not so small, it's 1366x768. Isn't possible to reduce the left and right margins?

I think it will impact the general look of plugins' website and make it a bit different from the main website. But I think it would be okay to reduce them for some inches. I will try and see how it will look. I will also add the missing columns.

> I think the table view is useful. I've also noticed that the choice between grid and table view doesn't stick: if you choose the table view and then click on the "Next" button, then the list is shown again as a grid. The same occurs if you go from e.g. the "All plugins" list to the "New plugins" list.

Yes, the view choice is not memorised yet. I will probably use the local storage for it. 

> I would also suggest to add a simple description on each list page on how the list is generated / sorted (e.g. the "Popular" list name is not self explanatory).
> It seems to me the "Stable" list should not be in "Top", but probably in "Category".

Those are well noted, thank you. I will also fix them.

Many thanks for the reviews. Your feedback is greatly appreciated. Please feel free to let me know if you notice anything else that needs attention.

**Comment by Xpirix** [comment]
Thank you very much for the feedback @kannes. I will take a look and try to fix each point.

**Comment by agiudiceandrea** [comment]
Thanks for implementing all the suggestions!
I would add some details for the lists description. For example "List of plugins that have been recently updated." could be "List of plugins that have been updated in the last 30 days" (if I'm not wrong). The same for the recently created plugins. It seems to me "popular" is still not so clear... maybe something like "based on number of downloads rating and votes"?
https://github.com/Xpirix/QGIS-Plugins-Website/blob/f0506f48beba32b4ead7646b059022d92472491d/qgis-app/plugins/models.py#L213)

**Pull request merged**
